finished styles of header
AlexandrHavrylov/c0de_w13ards_filmoteka pull request #17
Opened 2021-08-08 16:13 UTC by Baklaikin

2021-08-08 16:46 UTC, OleksandrSemak requested changes

2021-08-08 16:46 UTC, OleksandrSemak commented on src/sass/components/_header-home.scss
> +  @media (min-width: 768px) {
Предлагаю сразу тут юзать уже созданный миксин из variables:
@include tablet {
     width: 768px;
    background-image: url('../images/header-home-768.jpg');
  }

2021-08-08 16:46 UTC, OleksandrSemak commented on src/sass/components/_header-home.scss
> +  @media (min-width: 1024px) {
Ну тут то же самое - миксин

2021-08-08 16:46 UTC, OleksandrSemak commented on src/sass/components/_header-home.scss
> +  @media (min-width: 768px) {
То же самое

2021-08-08 16:46 UTC, OleksandrSemak commented on src/sass/components/_header-home.scss
> +  @media (min-width: 1024px) {
То же самое

2021-08-08 16:46 UTC, OleksandrSemak commented on src/sass/components/_header-home.scss
> +.header__title {
Пишем ведь по mobile-first, поэтому предлагаю тут чуть поменять логику изложения - сначала стили для скрытия (потому что скрывается на мобилке, которая у нас считается до начала таблетки), а дальше, начиная с таблетки - показывать

2021-08-08 16:46 UTC, OleksandrSemak commented on src/sass/components/_header-home.scss
> +  font-family: Roboto;
Часть стилей не нужны. У нас по умолчанию Робото, 12 шрифт, 500 жирность. + line-height пишем по множителю (в данном случае 14рх/12рх = 1.17), а не в пикселях. По крайней мере на верстке так и делали

2021-08-08 16:46 UTC, OleksandrSemak commented on src/sass/components/_header-home.scss
> +// .header__home--btn {
А то, что закоменчено - это ненужно? Если не, то лучше убрать, чтоб не копить лишний код

2021-08-08 16:46 UTC, OleksandrSemak commented on src/sass/components/_header-home.scss
> +.container {
Такой класс лучше не юзать, у нас в файле common такой же класс юзается. Этот класс нам просто перезапишет класс, который контролит общий контейнер для контента. Може назови header__container, например, или типа такого

2021-08-08 16:46 UTC, OleksandrSemak commented on src/sass/components/_header-home.scss
> +  width: 100%;
А что контролит общую ширину контейнера, в котором форма лежит? Дело в том, что по макету для мобилки это правильно, но для таблетки и дальше форма стоит по центру и не должна занимать 100% родителя.

2021-08-08 16:46 UTC, OleksandrSemak commented on src/sass/components/_header-home.scss
> +  width: 100%;
UPD: Как я понял, у тебя форма занимает всю ширину хедера, а инпуты уже идут со своей шириной, и получается, что форма занимает места больше, чем должна в принципе. Ну короче я бы давал форме какие-то размеры, а на инпуты уже кидал width: 100%, чтоб их ширину контролила форма

2021-08-08 16:46 UTC, OleksandrSemak commented on src/sass/components/_header-home.scss
> +  font-family: Roboto;
Тут тоже лишние стили. В общем по всему тексту надо их убрать

2021-08-08 16:46 UTC, OleksandrSemak commented on src/sass/components/_header-home.scss
> +  width: 130px;
Это ж не общие стили для всех кнопок на странице? Если не, то надо стиль по БЭМу написать. Если да - надо вынести в common

2021-08-08 16:46 UTC, OleksandrSemak commented on src/sass/components/_header-home.scss
> +.is-hidden {
В твоем случае это не покатит. Тебе нужно не прятать визуально, а вообще убирать из разметки. Иначе через focus можно будет клацнуть по тому, чего быть не должно. Например, по кнопке или форму отправить

2021-08-08 18:19 UTC, Baklaikin commented on src/sass/components/_header-home.scss
> +  font-family: Roboto;
Исправлю

2021-08-08 18:21 UTC, Baklaikin commented on src/sass/components/_header-home.scss
> +.is-hidden {
В js мы же этот же клас добавлять будем. какая разница? Или рендерить разметку с учетов viewport?

2021-08-08 18:21 UTC, Baklaikin commented on src/sass/components/_header-home.scss
> +// .header__home--btn {
убрал

2021-08-08 18:21 UTC, Baklaikin commented on src/sass/components/_header-home.scss
> +  font-family: Roboto;
почистил стили

2021-08-08 18:24 UTC, Baklaikin commented on src/sass/components/_header-home.scss
> +  width: 100%;
форма всегда 100% общего контейнера, инпут подгоняю под макет

2021-08-08 18:36 UTC, Baklaikin commented on src/sass/components/_header-home.scss
> +.header__title {
сделал

2021-08-08 18:42 UTC, Baklaikin commented on src/sass/components/_header-home.scss
> +  @media (min-width: 768px) {
сделал, возможно частично

2021-08-08 18:52 UTC, Baklaikin commented
Спасибо за замечания!

2021-08-08 19:15 UTC, OleksandrSemak requested changes

2021-08-08 19:15 UTC, OleksandrSemak commented on src/sass/components/_header-home.scss
> +  @media (min-width: 768px) {
Ну это в любом случае не критично вообще. Потом можно будет через Ctrl + f понаходить и поправить, где надо будет

2021-08-08 19:15 UTC, OleksandrSemak commented on src/sass/components/_header-home.scss
> +  width: 100%;
Ну, по макету не похоже, на самом деле, что форма должна быть на 100% хедера (кроме мобилки). Хотя в теории это разве что может повлиять на позиционирование (я видел ты кнопку поиска абсолютно позиционировал относительно родителя, я так понял это как раз форма) - вот тогда гибкая форма может неккоректно отображаться. Ну можно либо обсудить с ребятами на коле, либо уже на протяжении проекта смотреть, как оно себя будет вести и тогда уже что-то предпринимать

2021-08-08 19:15 UTC, OleksandrSemak commented on src/sass/components/_header-home.scss
> +.container {
Не пойму, тут имя класса пофиксил чи не? Просто это важный момент. Иначе у всех верстка может поломаться из-за этого класса

2021-08-08 19:15 UTC, OleksandrSemak commented on src/sass/components/_header-home.scss
> +  width: 130px;
Тоже не пойму, пофиксил чи не. Тоже важный момент, так как мы пишем по БЭМу

2021-08-08 19:15 UTC, OleksandrSemak commented on src/sass/components/_header-home.scss
> +.is-hidden {
Разница в том, что когда этот класс ляжет на элемент, то элемент все равно останется в разметке, он останется в ДОМе, из-за чего с элементом можно будет взаимодействовать, а мы этого не хотим

2021-08-09 10:54 UTC, AlexandrHavrylov approved these changes
Нужно будет пофиксить замечания от Саши

2021-08-09 10:54 UTC, merged