Main markup
AlexandrHavrylov/c0de_w13ards_filmoteka pull request #4
Opened 2021-08-07 11:21 UTC by maksik2018

сделал разметку main

2021-08-07 13:11 UTC, AlexandrHavrylov requested changes

2021-08-07 13:11 UTC, AlexandrHavrylov commented on src/html/main.html
> +  <h1 class="visually-hidden">Main Title</h1>
Я думаю тут на h2, а h1 сделать в хедере "Filmoteka"

2021-08-08 06:21 UTC, maksik2018 commented
согласен, вчера поспешил, поменял с h1 на H2

2021-08-08 10:18 UTC, AlexandrHavrylov approved these changes

2021-08-08 10:19 UTC, merged