Feature/style
AlexandrHavrylov/c0de_w13ards_filmoteka pull request #70
Opened 2021-08-17 09:01 UTC by Baklaikin

2021-08-17 17:55 UTC, OleksandrSemak requested changes

2021-08-17 17:55 UTC, OleksandrSemak commented on src/html/footer.html
>      <p>&copy 2021 | All Rights Reserved |</p>
Добавь плз еще пробел вот тут (пометил кучей звездочек):
            All Rights Reserved |*****</p>     
Иначе оно слитно смотрится.

2021-08-17 17:55 UTC, OleksandrSemak commented on src/sass/components/_main-section.scss
> +  padding: 20px 0 0 0; //нижний изменил 40=>0
У нас пагинация должна быть в секции main (сейчас пагинация вне мэйна ошибочно, это пофиксим). Поэтому те стили, что были до этих правок, актуальны, нижний паддинг должен быть у секции main.
Короче говоря - нужно вернуть предыдущие стили.

2021-08-17 17:55 UTC, OleksandrSemak commented on src/sass/components/_main-section.scss
> +    padding: 60px 0 0; //добавил нижний паддинг 0
Ну тут то же самое

2021-08-17 17:55 UTC, OleksandrSemak commented on src/sass/components/_main-section.scss
> +  margin-bottom: 20px;
Тут так делать нельзя, так как ты таким стилем оставляешь нижний марджин и у последнего элемента на мобилке, а такого быть не должно. Стиль необходимо вернуть на тот, какой был.

2021-08-17 17:55 UTC, OleksandrSemak commented on src/sass/components/_main-section.scss
> +      margin-bottom: 0;
Пока не понимаю, как это работает (в конце у нас 2 элемента, а ты убираешь марджин только у одного из них, хотя по логике надо у обоих). Так или иначе так делать нельзя, так как в случае изменения кол-ва элементов в галерее, например, на 40, или, вместо 3 элементов на строке будет 4, тебе нужно будет лезть в код и менять все в зависимости от ситуации. Короче это не катит. Добавленную часть нужно удалить.

ВАЖНО!
На класс movie-list на размер экрана tablet необходимо добавить такой стиль - margin-bottom: -30px. Тогда все будет как по макету.

2021-08-17 17:55 UTC, OleksandrSemak commented on src/sass/components/_main-section.scss
>      box-shadow: 3px 3px 6px rgba(255, 107, 8, 0.25);
Надо box-shadow вынести в переменную. Но не критично

2021-08-17 17:55 UTC, OleksandrSemak commented on src/sass/components/_main-section.scss
> +  padding: 0 10px 0 10px; //изменил нижний паддинг на 0
Паддинг я добавлял не по макету, а чисто из-за визуала. Дело вкуса, но если убрать нижний паддинг, как ты сейчас сделал, может быть так, что текст будет не очень красиво стыковаться с box-shadow, и тогда смысла от добавления паддинга просто нет. Я бы вернул обратно, как было

2021-08-17 17:55 UTC, OleksandrSemak commented on src/sass/components/_modal.scss
>  .modal-movie__img img {
Судя по всему плохо класс написан. Насколько я вижу, класс modal-movie__img это типа тумба или общий контейнер, в который входят куча других элементов. Его нужно переименовать на, например, "modal-movie__thumb". А вот на картинку в разметке добавить класс modal-movie__img и убрать этот магический селектор, так будет логично. Иначе нет смысла от БЭМа в нашем случае

2021-08-17 17:55 UTC, OleksandrSemak commented on src/html/footer.html
>    <div class="container footer__content">
После правок все комменты, которые уже отработаны, необходимо удалить из кода.

2021-08-18 11:55 UTC, Baklaikin commented on src/sass/components/_main-section.scss
> +    padding: 60px 0 0; //добавил нижний паддинг 0
ok

2021-08-18 11:55 UTC, Baklaikin commented on src/sass/components/_main-section.scss
> +  padding: 20px 0 0 0; //нижний изменил 40=>0
ok

2021-08-18 11:57 UTC, Baklaikin commented on src/sass/components/_main-section.scss
> +  margin-bottom: 20px;
дал маржин всем и потом убрал у мобилки последний, а таблетка и комп- двум последним

2021-08-18 12:19 UTC, Baklaikin commented on src/sass/components/_main-section.scss
> +  padding: 20px 0 0 0; //нижний изменил 40=>0
Перебросил пагинацию в main

2021-08-18 16:30 UTC, AlexandrHavrylov approved these changes

2021-08-18 16:30 UTC, merged